### ISSUE TITLE
P 242 grok 오류

### ISSUE THREAD

**Issue by paikga3** [onlybooks/elasticstack#8]
github 코드를 그대로 복사해서 실행시켜도 _grokparsefailure 가 났습니다.
대괄호처리에 대한 부분을 넣었더니 정상적으로 나왔는데요.
해당부분의 누락이 수정되어야 하는 부분은 아닌지 다른 독자들을 위해 점검해주셨으면 합니다.

책 & github 코드
`
match => { "message" => "%{MY_TIMESTAMP:timestamp} * \[%{DATA:id}\] %{IP:ip} %{NUMBER:port:int} \[%{LOGLEVEL:level}\] \- %{DATA:msg}\."}
`

수정코드
`
match => { "message" => "\[%{MY_TIMESTAMP:timestamp}\] * \[%{DATA:id}\] %{IP:ip} %{NUMBER:port:int} \[%{LOGLEVEL:level}\] \- %{DATA:msg}\."}
`

**Comment by sw-jung** [comment]
오류 제보 감사합니다. 말씀해주신 대로 `%{MY_TIMESTAMP:timestamp}` 양 옆에 대괄호 `\[`, `\]`가 누락된 것을 확인했습니다.
코드에 반영했으며 정오표에도 등록하도록 하겠습니다.
